services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

    postyou_contao_facebook.listener.load_posts:
      class: 'Postyou\ContaoFacebookConnectorBasicBundle\EventListener\FbCronDispatcher'